### ISSUE TITLE
Migrate PV VMDKs to another datastore

### ISSUE THREAD

**Issue by txnw** [kubernetes/cloud-provider-vsphere#296] opened 2020-02-06 21:45 UTC
Hey,

we are running Kubernetes on VMWare using the vSphere Cloud Provider to allow Kubernetes to create and attach additional VMDKs on a separate Datastore for persistent volumes.
 
This works pretty well. But now we are about to replace our shared storage system.
Doing a “classic” storage vmotion does not help us for the PV because this would place all VMDKs inside the VMs configuration folder and rename the PV VMDKs to the VM name.
We checked different approaches but all do not respect the folder structure for the Kubernetes persistent volume VMDKs.
We would like to do a “hot” migration without any downtimes for the VMs.
 
Any ideas/hints/experiences/directions how we could do the migration?

Thanks,
Thomas

**Comment by dvonthenen** [comment] 2020-02-07 21:50
Hi @txnw! Are you using the in-tree cloud provider (ie `--provider=vsphere`) or the external cloud provider (`--provider=external`)? I assume this is probably for in-tree provider since this project repo doesn't handle storage at all.

I would probably ask this question in the kubernetes' #provider-vsphere channel (https://kubernetes.slack.com/archives/C9PGCDKV5) or since you are dealing with a production workload, it might be beneficial to reach out via support ticket.

Off the of my head and if you are using in-tree storage provider, a safe way would be create a new VMDK on the new storage array and then if the application supports it, setup a second application node in active/passive (aka master/slave) and failover the node. Don't forget backsup and verify them before attempting this! If the data is just a simple set of files, rsync could help. It just all depends on what the situation you are working with. In either case, support might be a good place to get an architected solution based on your needs.

**Comment by txnw** [comment] 2020-02-11 12:14
Hey, from what I see we use the in-tree provider (`--provider=vsphere`).
I will raise the question in the Slack channel as you mentioned, thanks for that hint!

We already started discussing internally how a workaround may look like without diving into each app.

We were just wondering that obviously either no one else every needed s/th like this or its so dead simple that no one talks about it :)

**Comment by dvonthenen** [comment] 2020-02-11 17:25
Since many of the people that work on the external provider (this repo) only deal with this cloud provider and the vsphere CSI driver, we don't know the best practices when it comes to handling migration issues on the in-tree provider.

Another option might be that you could also svMotion and selectively pick each storage array for each VMDK. I think you might also be able to specify which folder that VMDK lands in. It's been a while since I have done this, but I believe it could work. As always create a test workload and try many many many times.... validate it works... before running on a production workload.

**Comment by txnw** [comment] 2020-02-12 07:59
Hey,

thanks for your follow up, unfortunately that's the point were we get bitten quite fast.
When moving disks, VMWare places the VMDKs in folder that are named like the VM and names the VMDK also like the VM. So with PVC VMDKs like /kubernetepvc/pvc-123-456-789.vmdk we end in a chaos :). 
In the past there was an option to skip the renaming. We asked the VMware support and they confirmed that this is not possible anymore.

**Comment by dvonthenen** [comment] 2020-02-21 17:06
@txnw were you able to get any more assistance from the support ticket?

I think the problem is there are many limitations with the in-tree storage provider which is why those in-tree cloud/storage providers are being deprecated in favor of these external ones. For complete transparency, a migration path from in-tree to these external providers are still being worked on.

**Comment by txnw** [comment] 2020-03-03 08:35
Hey,
unfortunately no. There was an option in the old days to disable the renaming of vmware  but this option does not exist anymore.
We are now having a look into http://velero.io and will do probably a mix of migration with velro and replacing them with new empty ones on the new storage depending on the use case.

**Comment by dvonthenen** [comment] 2020-03-03 17:30
@txnw based on my understanding of the last version of Velero I looked at, you should know that Velero uses restic (https://github.com/restic/restic) to do backups. It doesn't use native vSphere snapshots which also means that if you are using live running VMs when taking your backup, applications will not be quiesced (data in memory will be flushed to disk) meaning they will resemble a backup that's crash-consistent. If you shutdown the apps safely and then perform the backup using Velero, that should be what you are looking for.

I'm going to close this issue in this since this CPI repo doesn't deal with k8s storage (or storage of any kind). I would recommend following up again with a support ticket or maybe also talking with the people that maintain the vSphere CSI repo.

/close

**Closed by dvonthenen** 2020-03-03 17:30 UTC

**Comment by rumans** [comment] 2020-07-23 11:05
Hey,
We needed to migrate from one storage to another and this worked for us.
It seems that vsphere in-tree driver only uses DS name and not any uid.
So moving to another DS with the same name as the original works properly.

* Create new DS  with **new_DS_name**
* Scale down all deployments/statefulset that use pv to 0, so the vmdk are unmounted from the workers vm.
* Be sure that no worker vm's use the **old_DS_name**
* Copy kubevols folder from **old_DS_name** to **new_DS_name**
* Rename **old_DS_name** to **old_DS_name.orig**
* Rename **new_DS_name** to **old_DS_name**
* Scale up again all deployments/statefulsets

As the DS name will be the same on vsphere, volumes are attached properly even if they are located elsewhere.
