### ISSUE TITLE
Handling Cases where Guest.Net is empty

### ISSUE THREAD

**Issue by doctori** [kubernetes/cloud-provider-vsphere#307] opened 2020-03-24 16:38 UTC
/kind feature

**What happened**:
In some cases VMs can stop posting Guest.Net information (still trying to understand why)
for exemple : 
```json 
adm-plerouge@peb4itcloud01:~$ govc vm.info -json my-machine-09 | jq .VirtualMachines[0].Guest
{
  "ToolsStatus": "toolsOk",
  "ToolsVersionStatus": "guestToolsUnmanaged",
  "ToolsVersionStatus2": "guestToolsUnmanaged",
  "ToolsRunningStatus": "guestToolsRunning",
  "ToolsVersion": "2147483647",
  "ToolsInstallType": "guestToolsTypeUnknown",
  "GuestId": "ubuntu64Guest",
  "GuestFamily": "linuxGuest",
  "GuestFullName": "Ubuntu Linux (64-bit)",
  "HostName": "my-machine-09.local.lan",
  "IpAddress": "10.25.136.124",
  "Net": null,
  "IpStack": null,
  "Disk": [
    {
      "DiskPath": "/",
      "Capacity": 8388009984,
      "FreeSpace": 5361049600
    },
    {
      "DiskPath": "/var",
      "Capacity": 8388009984,
      "FreeSpace": 6896181248
    },
    {
      "DiskPath": "/boot",
      "Capacity": 511647744,
      "FreeSpace": 253403136
    },
    {
      "DiskPath": "/opt",
      "Capacity": 5217320960,
      "FreeSpace": 4022816768
    },
    {
      "DiskPath": "/home",
      "Capacity": 1023303680,
      "FreeSpace": 950063104
    },
    {
      "DiskPath": "/tmp",
      "Capacity": 2080194560,
      "FreeSpace": 1963376640
    },
    {
      "DiskPath": "/var/lib/docker",
      "Capacity": 50973642752,
      "FreeSpace": 25457958912
    },
    {
      "DiskPath": "/boot/efi",
      "Capacity": 535805952,
      "FreeSpace": 529506304
    },
    {
      "DiskPath": "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-d3ab4bcd-4cf5-4da4-9a15-003baad2b58c/globalmount",
      "Capacity": 10501771264,
      "FreeSpace": 9910333440
    },
    {
      "DiskPath": "/var/lib/kubelet/pods/683546c2-df62-409b-b250-7c610e0a629b/volumes/kubernetes.io~csi/pvc-d3ab4bcd-4",
      "Capacity": 10501771264,
      "FreeSpace": 9910333440
    }
  ],
  "Screen": {
    "Width": 1024,
    "Height": 768
  },
  "GuestState": "running",
  "AppHeartbeatStatus": "appStatusGray",
  "GuestKernelCrashed": false,
  "AppState": "none",
  "GuestOperationsReady": true,
  "InteractiveGuestOperationsReady": false,
  "GuestStateChangeSupported": true,
  "GenerationInfo": null
}
```

**What you expected to happen**:
In this case by default it would be nice to use Guest.IpAddress since it seems to be more consistant.

**How to reproduce it (as minimally and precisely as possible)**:
It seems in some cases that a lot of sub interfaces - linked to calico. messes with the ability of the VMWare tools to send the right Guest.Net interfaces

**Anything else we need to know?**:
I can make a PR if that make sense

**Environment**:
- vsphere-cloud-controller-manager version: 1.1.0
- OS (e.g. from /etc/os-release): "Ubuntu 18.04.4 LTS"
- Kernel (e.g. `uname -a`):  4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Install tools: Rancher 2.3 (RKE)
- Others: I've Already opened an issue to VMWare because the Guest.Net should be consistent but no real anwser on this side.

**Comment by dvonthenen** [comment] 2020-03-26 17:09
Hi @doctori 

I will investigate this, but VMTools really needs to be configured correctly in order for the CPI to function normally. I believe even if we do put in this workaround, there will be other aspects of the CPI (and also CSI - specifically correlating the VHDs to K8s volumes) that will not function properly. 

The other consequence of implementing this functionality is if there are multiple IPv4 and/or IPv6 addresses, the value of what appears in the Guest.IpAddress will be indeterminate and the cluster might not function correctly.

Will look into this, but the recommendation is to use an up-to-date VMTools for all VMs in the k8s cluster.

**Comment by frapposelli** [comment] 2020-05-06 16:12
You could also try with another vmtools implementation that exists in vmware/govmomi called `toolbox` https://github.com/vmware/govmomi/tree/master/toolbox

**Comment by dvonthenen** [comment] 2020-06-05 16:35
I did a simple check and after disabling VMTools, the guest.ipAddress field is also unset. This also appears to be the root cause for this issue as well:
https://github.com/kubernetes/cloud-provider-vsphere/issues/338

![Uploading Screen Shot 2020-06-05 at 9.32.44 AM.png…](Unset guest.ipAddress)

**Comment by doctori** [comment] 2020-06-07 19:56
quick update on this one, 
filtering interfaces helped a lot, to have a stable guest information.
basically added 
`set guestinfo/exclude-nics "docker*,cali*,veth*,virbr*,flan*"`
in the `/etc/vmware-tools/tools.conf`
so the issue was that too many interfaces was comming up and the vcenter just ignored the whole block.

**Comment by dvonthenen** [comment] 2020-06-08 17:15
HI @doctori 

I can give that a try and see if that helps at all. We have been doing the filtering on the CPI side and wondering if all those device can cause the choking.

I have a PR that I need to test and see if it makes any impact or not. If not, I will try this combo (PR and your suggestion here).

**Comment by dvonthenen** [comment] 2020-06-08 19:30
Hi @doctori 

If you had the time, I added some code to attempt to make sure the guest info is obtained correctly. If you had the time, try deploying the image `dvonthenen/vsphere-cloud-controller-manager:latest` using the existing yaml.

**Comment by dvonthenen** [comment] 2020-06-24 17:21
Verified that the device/interface filtering is the root cause. Will use this issue to add documentation around this.

**Comment by dvonthenen** [comment] 2020-07-21 21:07
/close

PR 349 was merged

**Closed** 2020-07-21 21:07 UTC
Labels: kind/feature
